### ISSUE TITLE
gitbook网站怎么弄的，感觉挺漂亮的

### ISSUE THREAD

**Issue by x-haose** [byoungd/English-level-up-tips#100]
这个gitbook网站的网站是用开源版本搭建的，还是用的官方平台的啊，我用开源版本的总感觉弄不出这个效果

**Comment by momoedmoonlight** [comment]
您好！吴思瑶已收到您的邮件，祝您生活愉快！

**Comment by byoungd** [comment]
> 这个gitbook网站的网站是用开源版本搭建的，还是用的官方平台的啊，我用开源版本的总感觉弄不出这个效果

只需要按照Gitbook的要求简单配置一下即可
