### ISSUE TITLE
问反馈，谁会了

### ISSUE THREAD

**Issue by ramen-curator** [byoungd/English-level-up-tips#125]
1. 我看到有30k的关注量。
2. 看起来是2017年的文章，现在是2023年，也就是6年了。
3. 我读了一遍所有issue，没发现用后反馈

我有一个疑惑：
首先假定这篇文章有效 
在这个情况“访问量惊人，发布时间久远”的情况下，
应该有相当一部分尝试了这篇文章的建议，并且已经尝试过一段时间了。
那么，如果有效，这里怎么没有还愿的人，来报告他们的反馈。
所有尝试的人，都放弃了吗？
@所有人
@watcher

**Comment by ramen-curator** [comment]
@watcher
Sorry, I just want to notify the repo's watcher & such an expression is fun.
So I use the `@watcher`, & I didn't know there really was such a person.

**Comment by byoungd** [comment]
this is so funny！



---原始邮件---
发件人: "Ramen ***@***.***&gt;
发送时间: 2023年12月16日(周六) 晚上8:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [byoungd/English-level-up-tips] 问反馈 (Issue #125)




 
@watcher
 Sorry, I just want to notify the repo's watcher &amp; such an expression is fun.
 So I use the @watcher, &amp; I didn't know there really was such a person.

**Comment by byoungd** [comment]
> 1. 我看到有30k的关注量。
> 2. 看起来是2017年的文章，现在是2023年，也就是6年了。
> 3. 我读了一遍所有issue，没发现用后反馈
> 
> 我有一个疑惑： 首先假定这篇文章有效 在这个情况“访问量惊人，发布时间久远”的情况下， 应该有相当一部分尝试了这篇文章的建议，并且已经尝试过一段时间了。 那么，如果有效，这里怎么没有还愿的人，来报告他们的反馈。 所有尝试的人，都放弃了吗？ @所有人 @watcher

会的人已经不再纠结

**Comment by ramen-curator** [comment]
> > 1. 我看到有30k的关注量。
> > 2. 看起来是2017年的文章，现在是2023年，也就是6年了。
> > 3. 我读了一遍所有issue，没发现用后反馈
> > 
> > 我有一个疑惑： 首先假定这篇文章有效 在这个情况“访问量惊人，发布时间久远”的情况下， 应该有相当一部分尝试了这篇文章的建议，并且已经尝试过一段时间了。 那么，如果有效，这里怎么没有还愿的人，来报告他们的反馈。 所有尝试的人，都放弃了吗？ @所有人 @watcher
> 
> 会的人已经不再纠结

放弃的人也不再纠结。
什么人会纠结？要投入真金白银进去的人需要纠结，因为随意意味着真金白银的损失。
所以投时方考量一下相关方法、知识的权威性、售后评价，也是很自然合理的行为。
