### ISSUE TITLE
Are you a boy or a girl

### ISSUE THREAD

**Issue by rgarlik** [byoungd/English-level-up-tips#130]
Hello,

the picture of the girl in the `README.md` is very cute. Just thought if that was you. Let me know.
If not, close this issue.

Thank you

**Comment by byoungd** [comment]
> Hello,
> 
> the picture of the girl in the `README.md` is very cute. Just thought if that was you. Let me know. If not, close this issue.
> 
> Thank you

Thanks. 

I'm a man. The girl of this article is my lover.

**Comment by rgarlik** [comment]
Thank you, closing the issue now
