### ISSUE TITLE
集合程序猿之力，搞个蒙哥阅读器安卓版出来

### ISSUE THREAD

**Issue by hao-lee** [byoungd/English-level-up-tips#73]
[蒙哥阅读器IOS版](https://apps.apple.com/cn/app/id483247714)实在是英语阅读利器，可以碾压国内所有阅读软件，它的功能有：

* 点击查词(无需长按)
* 显示单词难度级别
* 生词本
* 在文中高亮生词
* 支持各种字典库
* 随意导入书籍
* 词频统计
* 阅读统计

可惜这软件没有安卓版，既然在座的都是程序员，请问诸位是否有兴趣搞个开源项目弄一个出来，在下很想搞一个，但是苦于不是安卓开发者，实在是无从下手啊。

**Comment by aron10** [comment]
做个小程序就可以了，不需要安卓

**Comment by vecpeng** [comment]
我想试试

**Comment by hiei17** [comment]
现在蒙哥新版叫 听阅
生词可以直接调 中文意思在下面

**Comment by iHTCboy** [comment]
买一台苹果手机 🥳

**Comment by 136136qwer** [comment]
真的很需要这个
