### ISSUE TITLE
gitbook 好像挂掉了

### ISSUE THREAD

**Issue by guowei-gong** [byoungd/English-level-up-tips#83]
https://byoungd.gitbook.io/english-level-up-tips/

有小伙伴能访问吗？

**Comment by nadirvishun** [comment]
同打不开

**Comment by DanielZhui** [comment]
打不开

**Comment by byoungd** [comment]
> 打不开

尝试修复了，但是gitbook似乎本身出现了一些问题

**Comment by guowei-gong** [comment]
> > 打不开
> 
> 尝试修复了，但是gitbook似乎本身出现了一些问题

修复后可以关闭这个 issue 通知我~

**Comment by zhilong-12138** [comment]
坐等修复

**Comment by byoungd** [comment]
> https://byoungd.gitbook.io/english-level-up-tips/
> 
> 有小伙伴能访问吗？



> > > 打不开
> > 
> > 
> > 尝试修复了，但是gitbook似乎本身出现了一些问题
> 
> 修复后可以关闭这个 issue 通知我~

链接已更新为 https://app.gitbook.com/s/h4N92NQapglwlURGsfxo/ 请测试一下 如果可以正常访问的话就可以关闭此issue了

**Comment by nadirvishun** [comment]
并不可以，这个链接应该是个内部链接，需要授权才行：
![image](https://user-images.githubusercontent.com/5761981/144694640-2993c919-2c32-405a-8d99-5740511732de.png)

**Comment by byoungd** [comment]
> > https://byoungd.gitbook.io/english-level-up-tips/
> > 有小伙伴能访问吗？
> 
> > > > 打不开
> > > 
> > > 
> > > 尝试修复了，但是gitbook似乎本身出现了一些问题
> > 
> > 
> > 修复后可以关闭这个 issue 通知我~
> 
> 链接已更新为 https://app.gitbook.com/s/h4N92NQapglwlURGsfxo/ 请测试一下 如果可以正常访问的话就可以关闭此issue了

似乎 gitbook.io 这个域名大陆是无法正常访问的

gitbook提供的public链接是：https://babyyoung.gitbook.io/english-level-up-tips/

测试一下是否可以打开吧

**Comment by nadirvishun** [comment]
我这边测试打不开，没有任何响应，超时，能上github一般都会有代理的。

**Comment by byoungd** [comment]
> 我这边测试打不开，没有任何响应，超时，能上github一般都会有代理的。

gitbook.io 网址在国内似乎无法使用 开代理也不行

**Comment by nadirvishun** [comment]
但是实际上只是你这个链接打不开，像是我随便找了一个：`https://taizilongxu.gitbooks.io/stackoverflow-about-python/content/part/1.html`是可以打开的。
