### ISSUE TITLE
[链接失效] 我们为何害怕与陌生人交流

### ISSUE THREAD

**Issue by WilliamColton** [byoungd/English-level-up-tips#93]
https://github.com/byoungd/English-level-up-tips/blob/master/part-2/why-we-are-afraid-to-communicate-with-strangers.md
点开链接提示 Page not found

**Comment by byoungd** [comment]
> https://github.com/byoungd/English-level-up-tips/blob/master/part-2/why-we-are-afraid-to-communicate-with-strangers.md 点开链接提示 Page not found

我会尽快修复这个问题。
